baseURL = 'https://astro.garden/'
languageCode = 'en-us'
title = 'Astro Garden'
disableKinds = ['taxonomy', 'term']

[markup.goldmark.renderer]
hardWraps = true

[services]
  [services.googleAnalytics]
    ID = 'G-380W2ZBVPH'