name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Read .hugoversion
      id: hugo-version
      run: echo "HUGO_VERSION=$(cat .hugoversion)" >> "${GITHUB_OUTPUT}"

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
        extended: true

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: ./build.sh
